// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class Mailbox_Stub
    extends java.rmi.server.RemoteStub
    implements MailboxInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_check_0;
    private static java.lang.reflect.Method $method_delete_1;
    private static java.lang.reflect.Method $method_deliver_2;
    private static java.lang.reflect.Method $method_deliver_3;
    private static java.lang.reflect.Method $method_transfert_4;
    
    static {
	try {
	    $method_check_0 = MailboxInterface.class.getMethod("check", new java.lang.Class[] {});
	    $method_delete_1 = MailboxInterface.class.getMethod("delete", new java.lang.Class[] {java.lang.String.class});
	    $method_deliver_2 = MailboxInterface.class.getMethod("deliver", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_deliver_3 = MailboxInterface.class.getMethod("deliver", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
	    $method_transfert_4 = MailboxInterface.class.getMethod("transfert", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Mailbox_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of check()
    public java.lang.String check()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_check_0, null, -7322218452020605578L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of delete(String)
    public boolean delete(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_delete_1, new java.lang.Object[] {$param_String_1}, 5261133481927706737L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deliver(String, String)
    public boolean deliver(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deliver_2, new java.lang.Object[] {$param_String_1, $param_String_2}, 70503819615318439L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deliver(String, String, String)
    public boolean deliver(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_deliver_3, new java.lang.Object[] {$param_String_1, $param_String_2, $param_String_3}, -189470019149453244L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of transfert(String)
    public boolean transfert(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_transfert_4, new java.lang.Object[] {$param_String_1}, 2476407719356274142L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
